#pragma once

#include <cstdint>
#include <random>
#include <vector>

namespace karity {

// Raw x86-64 machine code filler, meant for the native entry stub the
// injector builds around `call karity_vm_thunk` -- the VMProtect/Themida-
// style counterpart to obfuscate.h's bytecode-level junk/opaque predicates,
// but operating on real registers/flags before the VM ever gets involved.
//
// Both functions are architecturally no-ops: whatever they clobber (always
// just RAX and RFLAGS) is fully restored by the time they return, verified
// by tests/test_native_junk.cpp actually executing the generated bytes.
// This matters because this code runs *before* vm_thunk captures the
// native register file -- anything left dirty here would corrupt the VM's
// view of the original program's state.

void emit_native_junk(std::vector<uint8_t> &out, std::mt19937_64 &rng);

// max_nest_depth bounds how many additional opaque predicates may be nested
// inside this one's dead branch (each one found is, of course, exactly as
// dead as the one guarding it).
void emit_native_opaque_predicate(std::vector<uint8_t> &out, std::mt19937_64 &rng, int max_nest_depth = 2);

// A direct `call` to a junk-only subroutine (placed inline, reached only
// via the call -- a local `jmp` skips over it so nothing falls through),
// which does its usual register/flag-safe filler and `ret`s straight back.
// Purely cosmetic noise from the VM's point of view, architecturally a
// no-op like the other two -- but it gives IDA/disassemblers a real
// call/ret edge to a "function" that isn't one, muddying call-graph and
// function-boundary analysis rather than just padding straight-line code.
void emit_junk_call(std::vector<uint8_t> &out, std::mt19937_64 &rng);

} // namespace karity
