#pragma once

#include <cstdint>
#include <random>
#include <vector>

namespace karity {

// Raw x86-64 machine code filler, meant for the native entry stub the
// injector builds around `call karity_vm_thunk` -- the VMProtect/Themida-
// style counterpart to obfuscate.h's bytecode-level junk/opaque predicates,
// but operating on real registers/flags before the VM ever gets involved.
//
// Both functions are architecturally no-ops: whatever they clobber (always
// just RAX and RFLAGS) is fully restored by the time they return, verified
// by tests/test_native_junk.cpp actually executing the generated bytes.
// This matters because this code runs *before* vm_thunk captures the
// native register file -- anything left dirty here would corrupt the VM's
// view of the original program's state.

void emit_native_junk(std::vector<uint8_t> &out, std::mt19937_64 &rng);

// max_nest_depth bounds how many additional opaque predicates may be nested
// inside this one's dead branch (each one found is, of course, exactly as
// dead as the one guarding it).
void emit_native_opaque_predicate(std::vector<uint8_t> &out, std::mt19937_64 &rng, int max_nest_depth = 2);

// A direct `call` to a junk-only subroutine (placed inline, reached only
// via the call -- a local `jmp` skips over it so nothing falls through),
// which does its usual register/flag-safe filler and `ret`s straight back.
// Purely cosmetic noise from the VM's point of view, architecturally a
// no-op like the other two -- but it gives IDA/disassemblers a real
// call/ret edge to a "function" that isn't one, muddying call-graph and
// function-boundary analysis rather than just padding straight-line code.
void emit_junk_call(std::vector<uint8_t> &out, std::mt19937_64 &rng);

// Overlapping / misaligned-instruction anti-disassembly: a short `jmp`
// forward over a 1-3 byte "decoy" region whose first byte is the opcode of a
// long (>= 5-byte) instruction (E8 call, E9 jmp, 68 push imm32, B8+ mov
// imm32, 05/0D/25/2D/3D arith eax,imm32, ...). Execution always lands exactly
// past the decoy (the jmp target), so the decoy bytes are never executed --
// but a *linear-sweep* disassembler reading straight through decodes the
// decoy opcode as its full long form, swallowing the first few bytes of the
// real (post-decoy) instruction as that decoy's operand. The tool's
// instruction boundaries thus desynchronize from the CPU's: everything it
// prints after the decoy is misaligned garbage until it happens to resync.
// Architecturally a strict no-op (touches nothing -- decoy is pure data the
// jmp skips), verified by tests/test_native_junk_main.cpp executing it, and
// its desync effect is verified there against a real Zydis linear decode.
void emit_overlap_jump(std::vector<uint8_t> &out, std::mt19937_64 &rng);

// Same overlapping-decoy idea, but the skip is an always-taken *conditional*
// jump (`jnz` past an opaque `(reg|1)&1`, identical to the opaque-predicate
// carrier), so the decoy region sits in the branch's fall-through. A
// recursive-traversal disassembler (IDA), unable to prove the predicate
// constant, must decode that fall-through too -- and desyncs on it exactly
// like emit_overlap_jump desyncs a linear sweep. Register/flag-safe
// (pushfq/push ... pop/popfq bracketed like emit_native_opaque_predicate).
void emit_overlap_opaque(std::vector<uint8_t> &out, std::mt19937_64 &rng);

// The strong form that desyncs recursive traversal (IDA) on the *real*
// executed path, not just a dead branch. An always-taken `jnz +3` lands three
// bytes INTO a 5-byte decoy instruction (lead opcode + b1 + b2 + EB 00). A
// recursive disassembler decodes that decoy whole off the fall-through, so the
// taken target lands mid-instruction -- the classic "jump into the middle of
// an instruction" conflict IDA renders as broken/red. Yet the only bytes the
// CPU actually executes there are the trailing `EB 00` (jmp +0), which just
// falls through to the `pop reg`/`popfq` epilogue, so it stays a strict
// register/flag no-op. Unlike emit_overlap_jump (linear-sweep only), this one
// is meant to be visible in IDA on the entry stub the OEP/--entry jmp lands in.
void emit_overlap_midinsn(std::vector<uint8_t> &out, std::mt19937_64 &rng);

// Register-indirect control transfer that stops recursive-traversal
// disassembly (IDA) from following the flow at all -- the complement to the
// overlap primitives, which make code *look* broken but still let a recursive
// tool resync on the next known target. Emits `push reg; lea reg, [rip+disp];
// jmp reg; <decoy>; pop reg`: the `lea` materializes the address of the trailing
// `pop reg` RIP-relatively (so the displacement is self-contained -- no base
// relocation, correct under ASLR, position-independent exactly like the overlap
// decoys), then `jmp reg` transfers there. A recursive disassembler has no
// static target for `jmp reg`, so it stops decoding past this point and every
// following byte in the region is left undefined (not just misaligned). The CPU
// simply lands on `pop reg` and falls through; reg is push/pop-balanced, no flag
// is touched, RSP is restored -- a strict no-op, verified by
// tests/test_native_junk_main.cpp executing it. The optional 1-3 byte decoy
// (jumped over) additionally desyncs a linear sweep, like emit_overlap_jump.
void emit_indirect_jump(std::vector<uint8_t> &out, std::mt19937_64 &rng);

// Anti-step-over: defeats a debugger's "step over" (x64dbg F8) via return-address
// manipulation, while staying a strict runtime no-op. Emits `call stub; <trap>;
// stub: pushfq; add qword [rsp+8], imm8; popfq; ret`. The `call` pushes a return
// address R pointing at the trap region right after it; the stub then rewrites
// that saved return address (at [rsp+8], past the 8 bytes pushfq just pushed) to
// point *past* the trap, so `ret` lands on the blob's real continuation and the
// trap bytes are never executed on the real path. x64dbg's F8 implements step-over
// by planting a one-shot breakpoint at R (= call+5) and running the call full
// speed; because the stub redirects the return away from R, that breakpoint never
// fires -- step-over silently loses control and runs away instead of stopping
// after the call. (Note: F8 does not *execute* the trap and fault -- the CPU runs
// the same real path either way; the trap-byte-execution/desync effect belongs to
// the emit_overlap_* family. This primitive attacks automatic step-over, not the
// disassembly boundary.) The trap's first byte is a >= 5-byte decoy lead opcode,
// so a linear sweep additionally desyncs on it like emit_overlap_jump. call/ret is
// stack-balanced, the add's flags are pushfq/popfq-saved, no register is touched --
// a strict no-op, verified by tests/test_native_junk_main.cpp executing it.
void emit_antistepover_call(std::vector<uint8_t> &out, std::mt19937_64 &rng);

// Defeats the Hex-Rays decompiler's stack-pointer analysis for the enclosing
// function while staying a strict runtime no-op. Emits `pushfq; push reg;
// mov reg, rsp; and reg, 0x70; add reg, 0x10; sub rsp, reg; add rsp, reg;
// pop reg; popfq`. The `sub rsp, reg` is a *variable* (register) stack
// adjustment, which the decompiler cannot fold to a constant -- it reports
// "sp-analysis failed" / "positive sp value" and emits broken or refused
// pseudocode for the whole function. At runtime it's fully balanced: reg is
// (rsp & 0x70) + 0x10, i.e. a nonzero multiple of 16 in [16,128], so rsp only
// dips a small, 16-aligned, guard-page-safe amount and is restored by the
// matching `add rsp, reg` before any real instruction runs (reg is untouched
// between them, so the pair cancels regardless of its value). Sourcing reg from
// rsp is what makes it simultaneously bounded/aligned at runtime yet opaque to
// static analysis. reg is push/pop-balanced and flags are pushfq/popfq-saved,
// so RAX/RFLAGS/RSP all survive -- verified by tests/test_native_junk_main.cpp.
void emit_stack_noise(std::vector<uint8_t> &out, std::mt19937_64 &rng);

} // namespace karity
