# Embeds the runtime's per-translation-unit assembly/source text into a C++
# header, so the host tool can rewrite + recompile the runtime at protect time
# (the "obfuscate the blob functions" pipeline -- see src/native/runtime_rewrite.h).
#
# Invoked via `cmake -P` with:
#   -D OUT_FILE=...                    generated header path
#   -D SOURCES="name|isobf|path;..."   one entry per TU (fields split on '|',
#                                      since Windows paths contain ':'). `name`
#                                      is the filename
#                                      to write back at protect time (its
#                                      extension decides how gcc treats it: .s =
#                                      assemble-only, .S = preprocess+assemble);
#                                      `isobf` is 1 for .c-derived .s that may be
#                                      junk-rewritten, 0 for the hand-written .S
#                                      thunks that must stay byte-for-byte (their
#                                      prologue shape backs the injector's SEH
#                                      unwind entries).
#   -D LINK_FLAGS="flag;flag;..."      the exact link args to reproduce the blob.
#
# Each source is emitted as a C++ raw string literal (a rare delimiter avoids
# any escaping of the assembly text); a build-time guard rejects the unlikely
# case of that delimiter appearing inside a source.

cmake_policy(SET CMP0007 NEW)

if(NOT DEFINED OUT_FILE OR NOT DEFINED SOURCES)
    message(FATAL_ERROR "GenerateSourceHeader: OUT_FILE and SOURCES are required")
endif()

set(_delim "KRTSRC_9f3a")

set(_entries "")
set(_count 0)
foreach(entry IN LISTS SOURCES)
    string(REPLACE "|" ";" parts "${entry}")
    list(GET parts 0 _name)
    list(GET parts 1 _isobf)
    list(GET parts 2 _path)

    if(NOT EXISTS "${_path}")
        message(FATAL_ERROR "GenerateSourceHeader: source does not exist: ${_path}")
    endif()

    file(READ "${_path}" _text)
    if(_text MATCHES "\\)${_delim}\"")
        message(FATAL_ERROR "GenerateSourceHeader: raw-string delimiter collides with content of ${_path}")
    endif()

    string(APPEND _entries
        "    { \"${_name}\", ${_isobf}, R\"${_delim}(\n${_text}\n)${_delim}\" },\n")
    math(EXPR _count "${_count} + 1")
endforeach()

set(_flag_entries "")
foreach(flag IN LISTS LINK_FLAGS)
    string(APPEND _flag_entries "    \"${flag}\",\n")
endforeach()

file(WRITE "${OUT_FILE}"
"/* auto-generated by GenerateSourceHeader.cmake -- do not edit */
#ifndef KARITY_RUNTIME_SOURCES_H
#define KARITY_RUNTIME_SOURCES_H

struct KarityRuntimeSource {
    const char *name;         /* filename to write at protect time (ext picks gcc mode) */
    int is_obfuscatable;      /* 1 = .c-derived .s that may be junk-rewritten */
    const char *text;         /* verbatim source text */
};

static const KarityRuntimeSource karity_runtime_sources[] = {
${_entries}};

static const int karity_runtime_source_count = ${_count};

/* Exact link args that reproduce the freestanding runtime blob -- kept in sync
   with runtime/CMakeLists.txt's target_link_options (they share one list). */
static const char *karity_runtime_link_flags[] = {
${_flag_entries}};

#endif /* KARITY_RUNTIME_SOURCES_H */
")

message(STATUS "karity runtime sources: embedded ${_count} translation units")
