# Turns a freestanding-linked runtime image into an embeddable C header.
#
# Invoked via `cmake -P` with -D EXE_FILE=... -D BIN_FILE=... -D OUT_FILE=...
# -D SYMBOLS="sym1:MACRO1;sym2:MACRO2;..." -D NM_EXECUTABLE=... -D OBJDUMP_EXECUTABLE=...
#
# EXE_FILE is the linked-but-not-yet-flattened PE image (still has symbols);
# BIN_FILE is what `objcopy -O binary` produced from it. We need EXE_FILE
# only to look up where each symbol in SYMBOLS landed relative to the
# lowest-VMA loadable section, since that arithmetic is what objcopy's
# flattening implicitly performs on addresses. Each pair emits
# `#define MACRO offset`, so the host tool can find that symbol's location
# within the flattened blob at protect time.

cmake_policy(SET CMP0007 NEW) # keep empty elements when splitting objdump output into lines

if(NOT EXISTS "${BIN_FILE}")
    message(FATAL_ERROR "GenerateBlobHeader: BIN_FILE does not exist: ${BIN_FILE}")
endif()

# --- locate each requested symbol's VMA ------------------------------------
execute_process(
    COMMAND "${NM_EXECUTABLE}" "${EXE_FILE}"
    OUTPUT_VARIABLE nm_output
    RESULT_VARIABLE nm_result
)
if(NOT nm_result EQUAL 0)
    message(FATAL_ERROR "GenerateBlobHeader: nm failed on ${EXE_FILE}")
endif()

# --- locate the lowest-VMA loadable section (objcopy's implicit base) ------
execute_process(
    COMMAND "${OBJDUMP_EXECUTABLE}" -h "${EXE_FILE}"
    OUTPUT_VARIABLE objdump_output
    RESULT_VARIABLE objdump_result
)
if(NOT objdump_result EQUAL 0)
    message(FATAL_ERROR "GenerateBlobHeader: objdump failed on ${EXE_FILE}")
endif()

set(lowest_vma "")
string(REPLACE "\n" ";" objdump_lines "${objdump_output}")

list(LENGTH objdump_lines n_lines)
math(EXPR last_idx "${n_lines} - 1")
foreach(i RANGE 0 ${last_idx})
    list(GET objdump_lines ${i} line)
    if(line MATCHES "^ *[0-9]+ +\\.[A-Za-z_.]+ +([0-9a-fA-F]+) +([0-9a-fA-F]+) +([0-9a-fA-F]+) +([0-9a-fA-F]+)")
        set(candidate_vma "${CMAKE_MATCH_2}")
        math(EXPR idx_plus_1 "${i} + 1")
        if(idx_plus_1 LESS_EQUAL last_idx)
            list(GET objdump_lines ${idx_plus_1} flagline)
            if(flagline MATCHES "CONTENTS, ALLOC, LOAD")
                math(EXPR candidate_dec "0x${candidate_vma}" OUTPUT_FORMAT DECIMAL)
                if(lowest_vma STREQUAL "" OR candidate_dec LESS lowest_vma)
                    set(lowest_vma "${candidate_dec}")
                endif()
            endif()
        endif()
    endif()
endforeach()

if(lowest_vma STREQUAL "")
    message(FATAL_ERROR "GenerateBlobHeader: could not find any loadable section in ${EXE_FILE}")
endif()

set(offset_defines "")
foreach(pair IN LISTS SYMBOLS)
    string(REPLACE ":" ";" pair_parts "${pair}")
    list(GET pair_parts 0 sym_name)
    list(GET pair_parts 1 macro_name)

    string(REGEX MATCH "([0-9a-fA-F]+) [A-Za-z] ${sym_name}\n" _ "${nm_output}\n")
    if(NOT CMAKE_MATCH_1)
        message(FATAL_ERROR "GenerateBlobHeader: symbol '${sym_name}' not found in ${EXE_FILE}")
    endif()
    math(EXPR sym_vma "0x${CMAKE_MATCH_1}" OUTPUT_FORMAT DECIMAL)

    math(EXPR sym_offset "${sym_vma} - ${lowest_vma}")
    if(sym_offset LESS 0)
        message(FATAL_ERROR "GenerateBlobHeader: computed negative offset for '${sym_name}' (${sym_offset})")
    endif()

    string(APPEND offset_defines "#define ${macro_name} ${sym_offset}u\n")
    message(STATUS "karity runtime blob: ${sym_name} -> ${macro_name} = ${sym_offset}")
endforeach()

# --- read the flattened blob and hex-encode it ------------------------------
file(READ "${BIN_FILE}" hex_content HEX)
string(LENGTH "${hex_content}" hex_len)
math(EXPR byte_count "${hex_len} / 2")

string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex_array "${hex_content}")
string(REGEX REPLACE "(0x[0-9a-f][0-9a-f],){12}" "\\0\n    " hex_array "${hex_array}")

file(WRITE "${OUT_FILE}"
"/* auto-generated by GenerateBlobHeader.cmake -- do not edit */
#ifndef KARITY_RUNTIME_BLOB_H
#define KARITY_RUNTIME_BLOB_H

#include <stdint.h>

#define KARITY_RUNTIME_BLOB_SIZE ${byte_count}u
${offset_defines}
static const uint8_t karity_runtime_blob[KARITY_RUNTIME_BLOB_SIZE] = {
    ${hex_array}
};

#endif /* KARITY_RUNTIME_BLOB_H */
")

message(STATUS "karity runtime blob: ${byte_count} bytes")
